---

- name: Copy mysql exporter script
  ansible.builtin.template:
    src: "mysql_exporter"
    dest: /usr/local/bin/mysql_exporter
    mode: 0755
    owner: root
    group: root

- name: Copy mysql exporter script
  ansible.builtin.template:
    src: "mysql_exporter.service"
    dest: /etc/systemd/system/mysql_exporter.service
    mode: 0644
    owner: root
    group: root

- name: Restart mysql exporter service is restarted
  ansible.builtin.service:
    name: Mysql_exporter
    state: restarted
    enabled: true
  changed_when: false

- name: Wait for mysql exporter to become ready
  ansible.builtin.wait_for:
    host: "{{ mysql_exporter_server_bind }}"
    port: "{{ mysql_exporter_server_port }}"
    state: started
    delay: 5
    connect_timeout: 15
    timeout: 300
