---
# handlers for ansible-role-docker-mysql_exporter

- name: Restart mysql_exporter
  ansible.builtin.service:
    name: Mysql_exporter
    state: restarted
    enabled: true

- name: Start mysql_exporter
  ansible.builtin.service:
    name: Mysql_exporter
    state: started
    enabled: true

- name: Reload mysql_exporter
  ansible.builtin.service:
    name: Mysql_exporter
    state: reloaded
    enabled: true
